# Server configuration
server.port=8080
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=${db.url:jdbc:mysql://localhost:3306/ecommjava?createDatabaseIfNotExist=true}
spring.datasource.username=${db.username:}
spring.datasource.password=${db.password:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=${hibernate.dialect:org.hibernate.dialect.MySQL8Dialect}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${hibernate.hbm2ddl.auto:update}

spring.devtools.restart.enabled=false