server.port=8082

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://database-1.cfq2as8eou0i.ap-south-1.rds.amazonaws.com:3306/ecommjava?createDatabaseIfNotExist=true
db.username=admin
db.password=3KdFaoNlszlUcqO51qFi

entitymanager.packagesToScan=com

spring.main.allow-circular-references=true
