db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://database-1.cfq2as8eou0i.ap-south-1.rds.amazonaws.com:3306/ecommjava?useSSL=false&allowPublicKeyRetrieval=true
db.username=admin
db.password=YOUR_PASSWORD

hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
entitymanager.packagesToScan=com.jtspringproject
