spring.datasource.url=jdbc:mysql://database-1.cfq2as8eou0i.ap-south-1.rds.amazonaws.com:3306/ecommjava?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
