-- MySQL Script generated by MySQL Workbench
-- Sun Feb 12 01:07:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema springproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema springproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `springproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`promotion_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`promotion_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`promotion_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`promotion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`promotion` (
  `id` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `promotionTypeId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `promotions_promotion_type_idx` (`promotionTypeId` ASC) VISIBLE,
  CONSTRAINT `promotions_promotion_type`
    FOREIGN KEY (`promotionTypeId`)
    REFERENCES `mydb`.`promotion_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `springproject`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springproject`.`user` ;

CREATE TABLE IF NOT EXISTS `springproject`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `role` ENUM('CUSTOMER', 'ADMIN') NOT NULL DEFAULT 'ROLE_USERS',
  `email` VARCHAR(320) NOT NULL,
  `address` VARCHAR(1000) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`parchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parchase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parchase` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `timeStamp` TIMESTAMP(20) NOT NULL,
  `total_price` DECIMAL(6,2) NOT NULL,
  `promotionId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `purchase_users_idx` (`userId` ASC) INVISIBLE,
  INDEX `FK_purchase_promotions_idx` (`promotionId` ASC) INVISIBLE,
  CONSTRAINT `FK_purchase_users`
    FOREIGN KEY (`userId`)
    REFERENCES `springproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_purchase_promotions`
    FOREIGN KEY (`promotionId`)
    REFERENCES `mydb`.`promotion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `springproject`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springproject`.`category` ;

CREATE TABLE IF NOT EXISTS `springproject`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springproject`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `springproject`.`product` ;

CREATE TABLE IF NOT EXISTS `springproject`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `imagePath` VARCHAR(255) NOT NULL,
  `categoryid` INT NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `salesCount` INT NULL,
  `isOnSale` TINYINT NULL,
  `discountPercent` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `products_ibfk_1` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`categoryid`)
    REFERENCES `springproject`.`category` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`purchase_details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`purchase_details` (
  `id` INT NOT NULL,
  `purchaseId` INT NULL,
  `productId` INT NULL,
  `quantity` INT NULL,
  `price` DECIMAL(6,2) NULL,
  `isOnSale` TINYINT NULL,
  `discountPercent` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_purchase_details_purchase_idx` (`purchaseId` ASC) VISIBLE,
  INDEX `FK_purchase_products_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `FK_purchase_details_purchase`
    FOREIGN KEY (`purchaseId`)
    REFERENCES `mydb`.`parchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_purchase_products`
    FOREIGN KEY (`productId`)
    REFERENCES `springproject`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favorite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`favorite` (
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  INDEX `FK_favorites_users_idx` (`userId` ASC) VISIBLE,
  INDEX `FK_favorites_products_idx` (`productId` ASC) VISIBLE,
  PRIMARY KEY (`userId`, `productId`),
  CONSTRAINT `FK_favorites_users`
    FOREIGN KEY (`userId`)
    REFERENCES `springproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_favorites_products`
    FOREIGN KEY (`productId`)
    REFERENCES `springproject`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `userId` INT NOT NULL,
  `productId` INT NOT NULL,
  `rating` TINYINT(5) NULL,
  PRIMARY KEY (`userId`, `productId`),
  INDEX `FK_ratings_products_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `FK_ratings_users`
    FOREIGN KEY (`userId`)
    REFERENCES `springproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ratings_products`
    FOREIGN KEY (`productId`)
    REFERENCES `springproject`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`search_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`search_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`search_history` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `phrase` VARCHAR(255) NOT NULL,
  `timeStamp` TIMESTAMP(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_search_history_users`
    FOREIGN KEY (`userId`)
    REFERENCES `springproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `springproject` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
