export const HOME_LIST_REQUEST = "HOME_LIST_REQUEST";
export const HOME_LIST_SUCCESS = "HOME_LIST_SUCCESS";
export const HOME_LIST_FAIL = "HOME_LIST_FAIL";

export const HOME_LIST_USER_REQUEST = "HOME_LIST_USER_REQUEST";
export const HOME_LIST_USER_SUCCESS = "HOME_LIST_USER_SUCCESS";
export const HOME_LIST_USER_FAIL = "HOME_LIST_USER_FAIL";

export const HOME_DELETE_REQUEST = "HOME_DELETE_REQUEST";
export const HOME_DELETE_SUCCESS = "HOME_DELETE_SUCCESS";
export const HOME_DELETE_FAIL = "HOME_DELETE_FAIL";
