export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGSITER_FAIL = "USER_REGSITER_FAIL";
export const USER_REGSITER_SUCCESS = "USER_REGSITER_SUCCESS";
export const USER_REGSITER_REQUEST = "USER_REGSITER_REQUEST";
